from typing import Optional, Protocol, Sequence
from ..models import MotorCommand, QRResultKind

class Vehicle(Protocol):
    def read_line_sensors(self) -> Sequence[bool]: ...
    def set_motors(self, command: MotorCommand) -> None: ...
    def cleanup(self) -> None: ...

class Camera(Protocol):
    def set_position(self, position: str) -> None: ...
    def poll(self) -> tuple[QRResultKind, Optional[str]]: ...
    def start_scan(self, scan_id: int) -> None: ...
    def cancel_scan(self, scan_id: int) -> None: ...
